### ISSUE TITLE
update szkript hiányosság?

### ISSUE THREAD

**Issue by attuska** [uhulinux/uhu-installer-ubk#1]
Az update szkript tényleg nem generál jófordítási pot fájlt.
Ez például hiányzik:

You must have a / mount point

Ezért ez a hibajelzés angolul jelenik még meg

**Comment by attuska** [comment]
Ez az egyetlen, nem lefordított.
Próbáltam az update szkriptbe belevenni a sprintf szócskát a keywordok közé.
Ekkormármegtalálja ezt is, beilleszti a pot fájlba. Ezután lefordítottam a poedittel ezt a részt,de ennek ellenére továbbra is angolul jelenik meg a felbukkanó ablak, holott a mo fájlban is benne van a fordítás.
Valamit biztosan elrontok.

**Comment by rezso** [comment]
Így jó?
https://github.com/uhulinux/uhu-installer-ubk/commit/46101a25ee85f76fa73051ca5e3883688a043823

**Comment by attuska** [comment]
oot@gubigep:/usr/src/UHUBUILD/UB-3/uhu-installer# uhu-installer
Too many arguments for main::_ at /usr/sbin/uhu-installer line 482, near "$fs)"
Bareword "create_disks_model" not allowed while "strict subs" in use at /usr/sbin/uhu-installer line 1364.
Bareword "create_grub_model" not allowed while "strict subs" in use at /usr/sbin/uhu-installer line 1365.
Bareword "fill_grub_model" not allowed while "strict subs" in use at /usr/sbin/uhu-installer line 1366.
Execution of /usr/sbin/uhu-installer aborted due to compilation errors.
root@gubigep:/usr/src/UHUBUILD/UB-3/uhu-installer#
